### ISSUE TITLE
Can't find file: 'example/ATPa1/search_list.txt'

### ISSUE THREAD

**Issue by stig42** [brightrao/ATPdock#1]
Hello,

When running ATPdock with the provided example I get the following error:

```
$ python ATPdock.py example
search template
There is no example/ATPa1
template is done
Traceback (most recent call last):
  File "/home/stig/atpdock/ATPdock/ATPdock.py", line 417, in <module>
    file = open(workpath + '/search_list.txt')
FileNotFoundError: [Errno 2] No such file or directory: 'example/ATPa1/search_list.txt'
```

Seems to be related to a call of `searchtm()`

Best regards,

**Comment by brightrao** [comment]
Dear,


Thanks for your email. 


In the standalone package of ATPdock, the input parameter should be the absolute path of the work folder, which only contains three files, i.e., "pdb.pdb", "tem.txt", and "pdb.site". For example, if the work folder is saved at "D:/xxx/yyy/example", we should use the following command to run the program of ATPdock:


    >python3 ATPdock.py D:/xxx/yyy/example
    
P.S., before you run the ATPdock program, please make sure that the input folder only contains the above three files. We strongly suggest you to use "python3" to execute the above command. 


If you have any questions, please contact us asap.


Sincerely yours.


Liang Rao, Ningxin Jia, Jun Hu, Dongjun Yu, Guijun Zhang



At 2021-07-25 01:30:18, "stig42" ***@***.***> wrote:

Hello,

When running ATPdock with the provided example I get the following error:

$ python ATPdock.py example
search template
There is no example/ATPa1
template is done
Traceback (most recent call last):
  File "/home/stig/atpdock/ATPdock/ATPdock.py", line 417, in <module>
    file = open(workpath + '/search_list.txt')
FileNotFoundError: [Errno 2] No such file or directory: 'example/ATPa1/search_list.txt'


Seems to be related to a call of searchtm()

Best regards,

**Comment by stig42** [comment]
Thanks, that helped. I have a different error now, related to a file called `Config.properties`
```
~/atpdock/ATPdock $ python /home/stig/atpdock/ATPdock/ATPdock.py /home/stig/atpdock/ATPdock/example
search template
ATPa1 is processing...
aaa
bbb
ccc
36485 0 36484
isPPSalign_or_APoc = 2
VKEFLAKAKEDFLKKWETPSQNTAQLDQFDRIKTLGTGSFGRVMLVKHKESGNHYAMKILDKQKVVKLKQIEHTLNEKRILQAVNFPFLVKLEFSFKDNSNLYMVMEYVAGGEMFSHLRRIGRFSEPHARFYAAQIVLTFEYLHSLDLIYRDLKPENLLIDQQGYIQVTDFGFAKRVKGRTWTLCGTPEYLAPEIILSKGYNKAVDWWALGVLIYEMAAGYPPFFADQPIQIYEKIVSGKVRFPSHFSSDLKDLLRNLLQVDLTKRFGNLKNGVNDIKNHKWFATTDWIAIYQRKVEAPFIPKFKGPGDTSNFDDYEEEEIRVSINEKCGKEFTEF
java.io.FileNotFoundException: /home/stig/atpdock/ATPdock/PPS-search/java/src/Config.properties (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at _util.PropUtil.loadProperties(PropUtil.java:12)
        at _util.PropUtil.loadPropertiesInHashMap(PropUtil.java:24)
        at _util.ConfigUtil.loadConfig(ConfigUtil.java:16)
        at _util.ConfigUtil.getConfig(ConfigUtil.java:21)
        at _util._Log.dayRunLog(_Log.java:80)
        at process.PPSsearch.saveErrorHtml(PPSsearch.java:350)
        at process.PPSsearch.main(PPSsearch.java:93)
        at submit.main(submit.java:55)
template is done
Traceback (most recent call last):
  File "/home/stig/atpdock/ATPdock/ATPdock.py", line 417, in <module>
    file = open(workpath + '/search_list.txt')
FileNotFoundError: [Errno 2] No such file or directory: '/home/stig/atpdock/ATPdock/example/ATPa1/search_list.txt'
```

**Comment by brightrao** [comment]
Dear,

Thanks for your email. Do you download the ATPdock-depended database (i.e., PL_DB (see the description of "Creating pocket-ligand database(PLDB)" in the README.md file)) and put it on the right position? It may be the reason of this problem you found.

We are very sorry for that the steps for using the standalone version of ATPdock have not written in detail. We will provide a new standalone version of ATPdock that is easier to configure and run in 2 to 3 days.

Sorry again for the inconvenience. If you have any questions, please contact us asap.

Sincerely yours.

Liang Rao, Ningxin Jia, Jun Hu, Dongjun Yu, Guijun Zhang





At 2021-07-27 02:11:48, "stig42" ***@***.***> wrote:

Thanks, that helped. I have a different error now, related to a file called Config.properties

~/atpdock/ATPdock $ python /home/stig/atpdock/ATPdock/ATPdock.py /home/stig/atpdock/ATPdock/example
search template
ATPa1 is processing...
aaa
bbb
ccc
36485 0 36484
isPPSalign_or_APoc = 2
VKEFLAKAKEDFLKKWETPSQNTAQLDQFDRIKTLGTGSFGRVMLVKHKESGNHYAMKILDKQKVVKLKQIEHTLNEKRILQAVNFPFLVKLEFSFKDNSNLYMVMEYVAGGEMFSHLRRIGRFSEPHARFYAAQIVLTFEYLHSLDLIYRDLKPENLLIDQQGYIQVTDFGFAKRVKGRTWTLCGTPEYLAPEIILSKGYNKAVDWWALGVLIYEMAAGYPPFFADQPIQIYEKIVSGKVRFPSHFSSDLKDLLRNLLQVDLTKRFGNLKNGVNDIKNHKWFATTDWIAIYQRKVEAPFIPKFKGPGDTSNFDDYEEEEIRVSINEKCGKEFTEF
java.io.FileNotFoundException: /home/stig/atpdock/ATPdock/PPS-search/java/src/Config.properties (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at _util.PropUtil.loadProperties(PropUtil.java:12)
        at _util.PropUtil.loadPropertiesInHashMap(PropUtil.java:24)
        at _util.ConfigUtil.loadConfig(ConfigUtil.java:16)
        at _util.ConfigUtil.getConfig(ConfigUtil.java:21)
        at _util._Log.dayRunLog(_Log.java:80)
        at process.PPSsearch.saveErrorHtml(PPSsearch.java:350)
        at process.PPSsearch.main(PPSsearch.java:93)
        at submit.main(submit.java:55)
template is done
Traceback (most recent call last):
  File "/home/stig/atpdock/ATPdock/ATPdock.py", line 417, in <module>
    file = open(workpath + '/search_list.txt')
FileNotFoundError: [Errno 2] No such file or directory: '/home/stig/atpdock/ATPdock/example/ATPa1/search_list.txt'

**Comment by jun-csbio** [comment]
We have proposed a new standalone package of ATPdock, which is esay to configure and available at https://github.com/jun-csbio/ATPdock.  Please use it. Thanks a lot.

**Comment by jun-csbio** [comment]
> Thanks, that helped. I have a different error now, related to a file called `Config.properties`
> 
> ```
> ~/atpdock/ATPdock $ python /home/stig/atpdock/ATPdock/ATPdock.py /home/stig/atpdock/ATPdock/example
> search template
> ATPa1 is processing...
> aaa
> bbb
> ccc
> 36485 0 36484
> isPPSalign_or_APoc = 2
> VKEFLAKAKEDFLKKWETPSQNTAQLDQFDRIKTLGTGSFGRVMLVKHKESGNHYAMKILDKQKVVKLKQIEHTLNEKRILQAVNFPFLVKLEFSFKDNSNLYMVMEYVAGGEMFSHLRRIGRFSEPHARFYAAQIVLTFEYLHSLDLIYRDLKPENLLIDQQGYIQVTDFGFAKRVKGRTWTLCGTPEYLAPEIILSKGYNKAVDWWALGVLIYEMAAGYPPFFADQPIQIYEKIVSGKVRFPSHFSSDLKDLLRNLLQVDLTKRFGNLKNGVNDIKNHKWFATTDWIAIYQRKVEAPFIPKFKGPGDTSNFDDYEEEEIRVSINEKCGKEFTEF
> java.io.FileNotFoundException: /home/stig/atpdock/ATPdock/PPS-search/java/src/Config.properties (No such file or directory)
>         at java.io.FileInputStream.open0(Native Method)
>         at java.io.FileInputStream.open(FileInputStream.java:195)
>         at java.io.FileInputStream.<init>(FileInputStream.java:138)
>         at java.io.FileInputStream.<init>(FileInputStream.java:93)
>         at _util.PropUtil.loadProperties(PropUtil.java:12)
>         at _util.PropUtil.loadPropertiesInHashMap(PropUtil.java:24)
>         at _util.ConfigUtil.loadConfig(ConfigUtil.java:16)
>         at _util.ConfigUtil.getConfig(ConfigUtil.java:21)
>         at _util._Log.dayRunLog(_Log.java:80)
>         at process.PPSsearch.saveErrorHtml(PPSsearch.java:350)
>         at process.PPSsearch.main(PPSsearch.java:93)
>         at submit.main(submit.java:55)
> template is done
> Traceback (most recent call last):
>   File "/home/stig/atpdock/ATPdock/ATPdock.py", line 417, in <module>
>     file = open(workpath + '/search_list.txt')
> FileNotFoundError: [Errno 2] No such file or directory: '/home/stig/atpdock/ATPdock/example/ATPa1/search_list.txt'
> ```

We have sorry for the above question. In order to avoid this configure question, we have proposed a new standalone package of ATPdock, which is esay to configure and available at https://github.com/jun-csbio/ATPdock. Please use it. Thanks a lot.

**Comment by stig42** [comment]
The repository at https://github.com/jun-csbio/ATPdock made it very easy to download the PLDB and to set everything up. I got it working now... thank you very much!
